# Generated by Django 4.1.7 on 2023-04-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_remove_newsarticle_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="content",
            field=models.CharField(max_length=2000),
        ),
    ]
