# Generated by Django 4.1.7 on 2023-04-19 02:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community_Forums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True, default=uuid.uuid4, unique=True
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.CharField(max_length=600)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.JSONField(default=list)),
                ("votes", models.IntegerField()),
                ("creator_email", models.EmailField(max_length=254)),
                ("creator_name", models.TextField()),
                ("creator_image", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Community Forums",
            },
        ),
        migrations.CreateModel(
            name="Forums_Votes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.TextField(default="No")),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.community_forums",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Forums Votes",
            },
        ),
        migrations.AddField(
            model_name="community_forums",
            name="user_votes",
            field=models.ManyToManyField(
                related_name="User", through="forum.Forums_Votes", to="user.profile"
            ),
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=3000)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.community_forums",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comments",
            },
        ),
    ]
